name: high_q_dio_logger
description: "A powerful, customizable, and beautifully formatted HTTP traffic logger interceptor for Dio. Features cURL generation, body formatting, rate limiting, and sensitive data sanitization."
version: 0.0.1
homepage: "https://github.com/azabcodes/high_q_dio_logger"

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

